name: Release

on:
  push:
    tags: ["v*.*.*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - path: services/orders-service
            name: orders-service
          - path: services/fleet-service
            name: fleet-service
          - path: services/tracking-service
            name: tracking-service
          - path: services/api-gateway
            name: api-gateway
         
    steps:
      - uses: actions/checkout@v4

      # 1. Extracts metadata (tags, labels) for Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ matrix.name }}
          tags: |
            type=semver,pattern={{version}}
            type=sha
            latest

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 2. Build and push using the extracted metadata
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.path }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
